services:
  openmsx:
    build: .
    container_name: openmsx
    ports:
      - "6080:6080"
      - "5900:5900"
    environment:
      DISPLAY: ":99"
    volumes:
      - ./roms:/home/dev/roms
      - ./systemroms:/home/dev/.openMSX/share/systemroms
    stdin_open: true
    tty: true
